version: "3"
services:
 client:
  build: .
  image: client:custom
  container_name: client
  tty: true
  networks:
   net-10.9.0.0:
    ipv4_address: 10.9.0.7

networks:
 net-10.9.0.0:
  name: net-10.9.0.0
  ipam:
   config:
    - subnet: 10.9.0.0/24
