version: '3'
services:
 website:
  build: ./
  image: dvwa:custom
  container_name: dvwa
  ports:
   - "80:80"
  networks:
   net-10.9.0.0:
    ipv4_address: 10.9.0.5
   
networks:
 net-10.9.0.0:
  name: net-10.9.0.0
  ipam:
   config:
    - subnet: 10.9.0.0/24
