version: '3'
services:
 website:
  build: ./
  image: reverse-proxy-nginx
  container_name: proxyNginx
  ports:
   - "80:80"
  networks:
   net-10.9.0.0:
    ipv4_address: 10.9.0.5

networks:
 net-10.9.0.0:
  name: net-10.9.0.0
  ipam:
   config:
    - subnet: 10.9.0.0/24
